# Generated by Django 4.2.20 on 2025-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0002_alter_cliente_email_alter_cliente_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="email",
        ),
        migrations.AlterField(
            model_name="fotografo",
            name="especialidade",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="fotografo",
            name="nome",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="fotografo",
            name="telefone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
