# Generated by Django 3.2.25 on 2025-09-04 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0003_remove_cliente_email_alter_fotografo_especialidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('duracao', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('finalizado', models.BooleanField(default=False)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.cliente')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.fotografo')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessaofoto',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='sessaofoto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='sessaofoto',
            name='estudio',
        ),
        migrations.RemoveField(
            model_name='sessaofoto',
            name='fotografo',
        ),
        migrations.DeleteModel(
            name='Estudio',
        ),
        migrations.DeleteModel(
            name='SessaoFoto',
        ),
    ]
