# Generated by Django 4.2.5 on 2025-09-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0005_auto_20250903_2323"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografo",
            name="foto_perfil",
            field=models.URLField(blank=True, null=True),
        ),
    ]
