# Generated by Django 4.2.5 on 2025-09-22 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0006_fotografo_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_url", models.URLField()),
                ("descricao", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fotografo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginas.fotografo",
                    ),
                ),
            ],
        ),
    ]
